### ISSUE TITLE
gym.error.UnregisteredEnv: No registered env with id: FreewheelingIntersection-v1

### ISSUE THREAD

**Issue by wanguangxi** [Metro1998/P-DQN#1]
Hello, would you mind writing a tutorial of your code?
such as install dependence , run command, etc.

Thank you, and look forward!

**Comment by Metro1998** [comment]
1.This repository is  similar with the original PDQN in https://github.com/cycraig/MP-DQN, but some modifications to fit my research. Therefore you can refer to MP-PDQN for more help.
2. About the env's error, it should be registered in gym, you can refer to baidu or  google for a more detailed guide.
Besides i haven't push my raw env into this repository (consideration of my paper)
3. If you are searching for a RL algorithm with hybrid action space, i recommend you HPPO(2019, sjtu), the implementation
is not so difficult according to its paper.
4. No more tutorial, but you can expect my hppo in about three months after my paper is submitted

**Comment by wanguangxi** [comment]
OK! Thank you!

**Comment by Metro1998** [comment]
problem solved

**Comment by wanguangxi** [comment]
Thanks for your hard work. I have a question about hybrid action space. If I have three level action structure, e.g., first level: discrete action A1; Second level: discrete action A2, that dependent A1; Three level : continuous action A3 that depend A2. A1 <--A2<--A3. for this kind of structure, would you mind sharing your idea about it ?

**Comment by Metro1998** [comment]
your email? and can you speak Chinese? I will send you a pdf to explain

**Comment by wanguangxi** [comment]
***@***.*** 动作空间由三层动作空间组成，第一层A1是离散的，第二层也是离散的A2。第二层依赖第一层，第一层动作下，有不同的离散动作A2, 第三层是第二层的参数-------- 原始邮件 --------发件人： Wolfie ***@***.***>日期： 2022年5月11日周三 中午11:07收件人： Metro1998/P-DQN ***@***.***>抄送： barrygxwan ***@***.***>, Author ***@***.***>主    题： Re: [Metro1998/P-DQN] gym.error.UnregisteredEnv: No registered env with id: FreewheelingIntersection-v1 (Issue #1)
your email? and can you speak Chinese? I will send you a pdf to explain

**Comment by Metro1998** [comment]
you can refer to https://zhuanlan.zhihu.com/p/513115809 for my recommendation
